# Generated by Django 3.1.4 on 2021-04-07 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agravamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agravamento',
            name='pacientes',
            field=models.ManyToManyField(blank=True, default=list, related_name='paciente_gravamentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
