# Generated by Django 3.1.4 on 2021-04-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=144)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('about', models.TextField(default='')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='image_perguntas/', verbose_name='Imagem')),
                ('pontos', models.IntegerField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('icon', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_pontos', models.IntegerField()),
                ('agravamentos_historico', jsonfield.fields.JSONField(default=list)),
                ('respostas_historicio', jsonfield.fields.JSONField(default=list)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datahora_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='PacienteResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('resposta', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.pergunta')),
            ],
            options={
                'db_table': 'agravamento_paciente_agravamento',
                'unique_together': {('paciente', 'pergunta')},
            },
        ),
    ]
